// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHoe_dbcontex;

#nullable disable

namespace SmartHoe_dbcontex.Migrations
{
    [DbContext(typeof(SmartHome_dbcontex))]
    [Migration("20260904154152_5")]
    partial class _5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity_class.Domain.Devices.DeviceReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("bit");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("float");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "RecordedAt");

                    b.ToTable("DeviceReadings", (string)null);
                });

            modelBuilder.Entity("smart_home_Asp.net.Domain.Devices.Base.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Roomid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Roomid");

                    b.ToTable("Devices", (string)null);

                    b.HasDiscriminator<string>("DeviceType").HasValue("Device");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("smart_home_Asp.net.Domain.Entities.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("smart_home_Asp.net.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("homeid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("homeid");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Entity_class.Domain.Devices.type.Fan", b =>
                {
                    b.HasBaseType("smart_home_Asp.net.Domain.Devices.Base.Device");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.ToTable("Devices", t =>
                        {
                            t.Property("IsOn")
                                .HasColumnName("Fan_IsOn");
                        });

                    b.HasDiscriminator().HasValue("Fan");
                });

            modelBuilder.Entity("Entity_class.Domain.Devices.type.Heater", b =>
                {
                    b.HasBaseType("smart_home_Asp.net.Domain.Devices.Base.Device");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.ToTable("Devices", t =>
                        {
                            t.Property("IsOn")
                                .HasColumnName("Heater_IsOn");
                        });

                    b.HasDiscriminator().HasValue("Heater");
                });

            modelBuilder.Entity("Entity_class.Domain.Devices.type.Light", b =>
                {
                    b.HasBaseType("smart_home_Asp.net.Domain.Devices.Base.Device");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.ToTable("Devices", t =>
                        {
                            t.Property("IsOn")
                                .HasColumnName("Light_IsOn");
                        });

                    b.HasDiscriminator().HasValue("Light");
                });

            modelBuilder.Entity("Entity_class.Domain.Devices.type.Rain_sensor", b =>
                {
                    b.HasBaseType("smart_home_Asp.net.Domain.Devices.Base.Device");

                    b.Property<double>("value_sensor")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("RainSensor");
                });

            modelBuilder.Entity("Entity_class.Domain.Devices.type.SecurityAlarm", b =>
                {
                    b.HasBaseType("smart_home_Asp.net.Domain.Devices.Base.Device");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("SecurityAlarm");
                });

            modelBuilder.Entity("Entity_class.Domain.Devices.type.door_sensor", b =>
                {
                    b.HasBaseType("smart_home_Asp.net.Domain.Devices.Base.Device");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("DoorSensor");
                });

            modelBuilder.Entity("smart_home_Asp.net.Domain.Devices.Base.Device", b =>
                {
                    b.HasOne("smart_home_Asp.net.Domain.Entities.Room", null)
                        .WithMany("Devices")
                        .HasForeignKey("Roomid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("smart_home_Asp.net.Domain.Entities.Room", b =>
                {
                    b.HasOne("smart_home_Asp.net.Domain.Entities.Home", null)
                        .WithMany("Rooms")
                        .HasForeignKey("homeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("smart_home_Asp.net.Domain.Entities.Home", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("smart_home_Asp.net.Domain.Entities.Room", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
